services:
  mysql_db:
    image: mysql:8.0
    container_name: library_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: library_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    container_name: library_backend
    restart: always
    environment:
      DATABASE_URL: mysql+pymysql://root:rootpassword@mysql_db:3306/library_db
      JWT_SECRET: SUPER_SECRET_JWT_KEY_987654321_LIBRARY_SYSTEM_2026
      ATTENDANCE_COOLDOWN_SECONDS: "300"
      FACE_RECOGNITION_THRESHOLD: "0.60"
      OVERDUE_FINE_PER_DAY: ${OVERDUE_FINE_PER_DAY:-}
      CAMERA_ID: ${CAMERA_ID:-}
      FACE_SERVICE_TOKEN: ${FACE_SERVICE_TOKEN:-}
      ATTENDANCE_TIMEZONE: ${ATTENDANCE_TIMEZONE:-Asia/Kolkata}
    ports:
      - "8000:8000"
    depends_on:
      - mysql_db
    volumes:
      - uploads_data:/app/uploads

  face_service:
    build:
      context: ../face_service
      dockerfile: Dockerfile
    container_name: library_face_service
    restart: always
    environment:
      MAIN_API_URL: http://backend:8000/api
      CAMERA_ID: ${CAMERA_ID:-}
      FACE_SERVICE_TOKEN: ${FACE_SERVICE_TOKEN:-}
      CAMERA_SOURCE: ${CAMERA_SOURCE:-0}
    ports:
      - "8001:8001"
    depends_on:
      - backend

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    container_name: library_frontend
    restart: always
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  mysql_data:
  uploads_data:
