import React, { useEffect, useMemo, useState } from 'react';
import { Link } from 'react-router-dom';
import { BookOpen, CalendarDays, Clock3, FileBarChart, Library, RefreshCw, UserCheck, Users } from 'lucide-react';
import { Cell, Pie, PieChart, ResponsiveContainer, Tooltip } from 'recharts';
import apiClient from '../api/axios';

const asDate = value => value && new Date(/(?:Z|[+-]\d{2}:\d{2})$/.test(value) ? value : `${value}Z`);
const time = value => value ? asDate(value).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' }) : '—';
const day = value => value ? new Date(`${value}T00:00:00`).toLocaleDateString([], { day: '2-digit', month: 'short' }) : '—';
const Empty = ({ children }) => <p className="py-10 text-center text-sm text-slate-500">{children}</p>;
const Card = ({ children, className = '' }) => <section className={`rounded-2xl border border-slate-200 bg-white p-5 shadow-sm ${className}`}>{children}</section>;
const Metric = ({ title, value, detail, icon: Icon, tone }) => <Card><div className="flex gap-4"><span className={`rounded-2xl p-3 ${tone}`}><Icon size={25} /></span><div><p className="text-sm text-slate-500">{title}</p><p className="mt-1 text-3xl font-bold text-slate-900">{value}</p><p className="mt-2 text-xs text-slate-500">{detail}</p></div></div></Card>;

export const Dashboard = () => {
  const [summary, setSummary] = useState(null);
  const [library, setLibrary] = useState(null);
  const [attendance, setAttendance] = useState([]);
  const [issues, setIssues] = useState([]);
  const [audits, setAudits] = useState([]);
  const [search, setSearch] = useState('');
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState('');

  const load = async () => {
    setLoading(true); setError('');
    try {
      const [summaryResponse, libraryResponse, attendanceResponse, issueResponse, auditResponse] = await Promise.all([
        apiClient.get('/dashboard/summary'), apiClient.get('/dashboard/library-summary'), apiClient.get('/attendance?limit=8'), apiClient.get('/book-issues?limit=8'), apiClient.get('/admin/audit-logs?limit=8')
      ]);
      setSummary(summaryResponse.data); setLibrary(libraryResponse.data); setAttendance(attendanceResponse.data); setIssues(issueResponse.data); setAudits(auditResponse.data);
    } catch (requestError) { setError(requestError.response?.data?.detail || 'Dashboard data could not be loaded.'); }
    finally { setLoading(false); }
  };
  useEffect(() => { load(); }, []);
  const attendanceMatches = useMemo(() => attendance.filter(session => `${session.student?.full_name || ''} ${session.student?.student_id || ''}`.toLowerCase().includes(search.toLowerCase())), [attendance, search]);
  const attendanceData = [{ name: 'Present', value: summary?.present_today || 0 }, { name: 'Absent', value: summary?.absent_today || 0 }];
  const libraryData = [{ name: 'Available', value: library?.available || 0 }, { name: 'Issued', value: library?.issued || 0 }, { name: 'Overdue', value: library?.overdue || 0 }];
  const dateLabel = new Date().toLocaleDateString([], { weekday: 'long', day: '2-digit', month: 'short', year: 'numeric' });

  const Donut = ({ values, colours, empty }) => values.some(item => item.value) ? <div className="h-48 w-1/2"><ResponsiveContainer><PieChart><Pie data={values} dataKey="value" innerRadius={52} outerRadius={76} paddingAngle={3}>{colours.map(colour => <Cell key={colour} fill={colour} />)}</Pie><Tooltip /></PieChart></ResponsiveContainer></div> : <div className="flex h-48 w-1/2 items-center justify-center text-center text-sm text-slate-500">{empty}</div>;

  return <div className="mx-auto max-w-[1600px] space-y-5 text-slate-900">
    <header className="flex flex-wrap items-center justify-between gap-4 rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><div><h1 className="text-3xl font-bold">Dashboard</h1><p className="mt-1 text-slate-500">Live overview of library operations and verified attendance.</p></div><div className="flex items-center gap-3"><span className="hidden rounded-xl border border-slate-200 bg-slate-50 px-4 py-3 text-sm text-slate-600 sm:block"><CalendarDays className="mr-2 inline text-blue-600" size={18} />{dateLabel}</span><button type="button" onClick={load} className="flex items-center gap-2 rounded-xl bg-blue-600 px-4 py-3 text-sm font-semibold text-white shadow-sm hover:bg-blue-700"><RefreshCw size={16} className={loading ? 'animate-spin' : ''} />Refresh</button></div></header>
    {error && <p role="alert" className="rounded-xl border border-rose-200 bg-rose-50 p-4 text-sm text-rose-700">{error}</p>}
    <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Metric title="Total Students" value={summary?.total_students ?? '—'} detail={`${summary?.active_students ?? 0} active registered students`} icon={Users} tone="bg-violet-100 text-violet-600" /><Metric title="Present Today" value={summary?.present_today ?? '—'} detail={`${summary?.today_attendance_percentage ?? 0}% of active students`} icon={UserCheck} tone="bg-emerald-100 text-emerald-600" /><Metric title="Total Books" value={summary?.total_books ?? '—'} detail={`${summary?.available_books ?? 0} copies currently available`} icon={BookOpen} tone="bg-rose-100 text-rose-500" /><Metric title="Books Issued" value={summary?.issued_books ?? '—'} detail={`${summary?.overdue_books ?? 0} overdue items need attention`} icon={Library} tone="bg-amber-100 text-amber-600" /></div>
    <div className="grid gap-5 xl:grid-cols-[1fr_1fr_0.8fr]">
      <Card><div className="mb-3 flex justify-between"><h2 className="font-bold">Today&apos;s Attendance</h2><Link to="/attendance/list" className="text-xs font-semibold text-blue-600">View log</Link></div><div className="flex items-center gap-4"><Donut values={attendanceData} colours={['#22c55e', '#f87171']} empty="No attendance records for today." /><div className="space-y-4 text-sm"><p><i className="mr-2 inline-block h-3 w-3 rounded-full bg-emerald-500" />Present <b className="ml-5">{summary?.present_today ?? 0}</b></p><p><i className="mr-2 inline-block h-3 w-3 rounded-full bg-red-400" />Absent <b className="ml-6">{summary?.absent_today ?? 0}</b></p><p><i className="mr-2 inline-block h-3 w-3 rounded-full bg-slate-300" />Inside <b className="ml-6">{summary?.currently_inside ?? 0}</b></p></div></div></Card>
      <Card><div className="mb-3 flex justify-between"><h2 className="font-bold">Library Status</h2><Link to="/books" className="text-xs font-semibold text-blue-600">Manage books</Link></div><div className="flex items-center gap-4"><Donut values={libraryData} colours={['#2563eb', '#f59e0b', '#ef4444']} empty="No catalogue data yet." /><div className="space-y-4 text-sm"><p><i className="mr-2 inline-block h-3 w-3 rounded-full bg-blue-600" />Available <b className="ml-3">{library?.available ?? 0}</b></p><p><i className="mr-2 inline-block h-3 w-3 rounded-full bg-amber-500" />Issued <b className="ml-8">{library?.issued ?? 0}</b></p><p><i className="mr-2 inline-block h-3 w-3 rounded-full bg-red-500" />Overdue <b className="ml-5">{library?.overdue ?? 0}</b></p></div></div></Card>
      <Card><h2 className="mb-4 font-bold">Quick Actions</h2><div className="grid grid-cols-2 gap-3"><Link to="/books" className="rounded-xl bg-blue-50 p-3 text-center text-xs font-semibold text-blue-700 hover:bg-blue-100"><BookOpen className="mx-auto mb-1" size={20} />Manage books</Link><Link to="/attendance/live" className="rounded-xl bg-emerald-50 p-3 text-center text-xs font-semibold text-emerald-700 hover:bg-emerald-100"><UserCheck className="mx-auto mb-1" size={20} />Live attendance</Link><Link to="/books/issue-return" className="rounded-xl bg-amber-50 p-3 text-center text-xs font-semibold text-amber-700 hover:bg-amber-100"><BookOpen className="mx-auto mb-1" size={20} />Issue / return</Link><Link to="/attendance/reports" className="rounded-xl bg-violet-50 p-3 text-center text-xs font-semibold text-violet-700 hover:bg-violet-100"><FileBarChart className="mx-auto mb-1" size={20} />Reports</Link></div></Card>
    </div>
    <div className="grid gap-5 xl:grid-cols-[1.1fr_1.1fr_0.8fr]">
      <Card className="overflow-hidden"><div className="mb-4 flex flex-wrap items-center justify-between gap-3"><div><h2 className="font-bold">Recent Attendance</h2><p className="text-xs text-slate-500">Verified check-in and check-out sessions</p></div><input value={search} onChange={event => setSearch(event.target.value)} placeholder="Search student or ID" className="rounded-xl border border-slate-200 bg-slate-50 px-3 py-2 text-xs outline-none focus:border-blue-500" /></div>{attendanceMatches.length ? <div className="overflow-x-auto"><table className="w-full text-left text-xs"><thead className="border-y border-slate-100 bg-slate-50 text-slate-500"><tr><th className="p-3">Student</th><th className="p-3">Check in</th><th className="p-3">Check out</th><th className="p-3">Status</th></tr></thead><tbody>{attendanceMatches.map(session => <tr key={session.id} className="border-b border-slate-100"><td className="p-3"><div className="flex items-center gap-2">{session.student?.profile_photo_path ? <img src={session.student.profile_photo_path} alt="" className="h-7 w-7 rounded-full object-cover" /> : <span className="flex h-7 w-7 items-center justify-center rounded-full bg-slate-100 font-bold">{session.student?.full_name?.[0] || 'S'}</span>}<div><p className="font-semibold text-slate-800">{session.student?.full_name}</p><p className="font-mono text-blue-600">{session.student?.student_id}</p></div></div></td><td className="p-3">{time(session.check_in_time)}</td><td className="p-3">{session.check_out_time ? time(session.check_out_time) : <span className="font-semibold text-amber-600">Inside library</span>}</td><td className="p-3"><span className="rounded-full bg-emerald-100 px-2 py-1 font-semibold text-emerald-700">{session.status}</span></td></tr>)}</tbody></table></div> : <Empty>{search ? 'No matching attendance session.' : 'No recorded activity yet.'}</Empty>}</Card>
      <Card><div className="mb-4 flex justify-between"><div><h2 className="font-bold">Recent Book Activity</h2><p className="text-xs text-slate-500">Issues and returns from the library</p></div><Link to="/books/issue-return" className="text-xs font-semibold text-blue-600">View all</Link></div>{issues.length ? <div className="space-y-2">{issues.slice(0, 5).map(issue => <div key={issue.id} className="grid grid-cols-[1.1fr_1.3fr_auto] items-center gap-2 rounded-xl bg-slate-50 px-3 py-3 text-xs"><div><p className="font-semibold text-slate-800">{issue.student_name || 'Student'}</p><p className="font-mono text-blue-600">{issue.student_code || '—'}</p></div><div><p className="font-medium text-slate-700">{issue.book?.title || 'Book'}</p><p className="text-slate-500">{day(issue.return_date || issue.issue_date)}</p></div><span className={`rounded-full px-2 py-1 font-semibold ${issue.status === 'RETURNED' ? 'bg-blue-100 text-blue-700' : issue.status === 'OVERDUE' ? 'bg-rose-100 text-rose-700' : 'bg-emerald-100 text-emerald-700'}`}>{issue.status}</span></div>)}</div> : <Empty>No recorded activity yet.</Empty>}</Card>
      <Card><div className="mb-4 flex justify-between"><h2 className="font-bold">System Activity</h2><Link to="/admin/settings" className="text-xs font-semibold text-blue-600">Settings</Link></div>{audits.length ? <div className="space-y-4">{audits.slice(0, 6).map(log => <div key={log.id} className="flex gap-3"><span className="mt-1 rounded-full bg-blue-100 p-2 text-blue-600"><Clock3 size={14} /></span><div><p className="text-sm font-semibold text-slate-800">{log.action.replaceAll('_', ' ')}</p><p className="mt-0.5 line-clamp-2 text-xs text-slate-500">{log.details || 'Administrator activity recorded.'}</p><p className="mt-1 text-xs text-slate-400">{time(log.timestamp)}</p></div></div>)}</div> : <Empty>No recorded activity yet.</Empty>}</Card>
    </div>
  </div>;
};
